### PR TITLE
Updated for Xcode 8 beta 6

### PR DESCRIPTION
**Pull request by sammygutierrez**
This should go into a new swift3 branch.
#49

### CODE REVIEW

**Comment by RemyDCF** [comment]
Thanks !

**Comment by tapz** [comment]
Could you please merge this and update the pod?

**Comment by arilsonkarmo** [comment]
is a good time to merge this!

**Comment by ryanholden8** [comment]
Yes, please merge! Thank you for the great UI component! :)

**Comment by D-Mx** [comment]
Any news regarding this?

**Comment by portwatcher** [comment]
If you are really in need of swift3 version of this repo to work with XCode 8, you can use this line in your `Podfile`

```
pod "DGElasticPullToRefresh", :git => 'https://github.com/sammygutierrez/DGElasticPullToRefresh.git', :branch => 'swift3'
```

You are at your own risk in this way, because this pr is not code reviewed by the owner.

**Comment by gontovnik** [comment]
Sorry guys for the delay. It is finally there. :)

**Pull request merged**
